"""QuantConnect plugin.

QuantConnect uses the LEAN engine. Local backtesting is done via the standard
Backtrader scaffold generated by the coder agent, which prints STRATENGINE_STATS.
No custom harness needed — engine uses the default script path.
"""
# No plugin registered — engine uses default path.
